# -*- coding: utf-8 -*-
"""AI study Assistant using less tokens.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WSqYEYMn5QXKjHNijh_wEOVMR31vEt-D
"""

# ============================================================
# 🧠 SMART AI STUDY ASSISTANT
# LangChain + Google Gemini
# Google Colab - SINGLE CELL
# ============================================================

!pip install -q -U langchain langchain-google-genai gradio


# ============================================================
# IMPORTS
# ============================================================

import os
import gradio as gr
from getpass import getpass

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser


# ============================================================
# 1. GEMINI API KEY
# ============================================================

print("🔑 Enter your Gemini API Key")

os.environ["GOOGLE_API_KEY"] = getpass("Gemini API Key: ")


# ============================================================
# 2. GEMINI MODEL
# ============================================================

llm = ChatGoogleGenerativeAI(
    model="gemini-3.6-flash",
    max_output_tokens=1200
)


# ============================================================
# 3. SMART PROMPT
# ============================================================

prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        """You are a smart AI Study Assistant.

Teach clearly, accurately and concisely.
Adapt the answer to the student's level and requested task.

Rules:
- Use simple language.
- Avoid unnecessary information.
- Use headings and bullet points.
- Give examples only when useful.
- For technical subjects, include syntax/formulas when relevant.
- For exam preparation, focus on high-value points.
- Never repeat the question.
- Keep responses concise unless detailed explanation is requested."""
    ),

    (
        "human",
        """Subject: {subject}
Topic: {topic}
Level: {level}
Task: {task}

Give the most useful answer for this student."""
    )
])


# ============================================================
# 4. LANGCHAIN CHAIN
# ============================================================

chain = prompt | llm | StrOutputParser()


# ============================================================
# 5. STUDY ASSISTANT
# ============================================================

def study_assistant(subject, topic, level, task):

    if not subject or not subject.strip():
        return "⚠️ Please enter a subject."

    if not topic or not topic.strip():
        return "⚠️ Please enter a topic."

    try:

        response = chain.invoke({
            "subject": subject.strip(),
            "topic": topic.strip(),
            "level": level,
            "task": task
        })

        return response

    except Exception as e:

        return f"""## ❌ Error

{str(e)}

Please check your Gemini API key and model access."""


# ============================================================
# 6. GRADIO UI
# ============================================================

with gr.Blocks(
    title="Smart AI Study Assistant"
) as demo:

    gr.Markdown("""
# 🧠 Smart AI Study Assistant

**LangChain + Google Gemini**

Learn concepts, prepare for exams, generate notes,
practice questions, or revise quickly.
""")


    with gr.Row():

        # ----------------------------------------------------
        # INPUT PANEL
        # ----------------------------------------------------

        with gr.Column(scale=1):

            subject = gr.Textbox(
                label="📚 Subject",
                placeholder="e.g. Computer Science"
            )

            topic = gr.Textbox(
                label="📝 Topic",
                placeholder="e.g. Operating System"
            )

            level = gr.Dropdown(
                [
                    "Beginner",
                    "School Student",
                    "College Student",
                    "Advanced"
                ],
                value="College Student",
                label="🎓 Level"
            )

            task = gr.Dropdown(
                [
                    "Explain",
                    "Exam Preparation",
                    "Short Notes",
                    "Practice Questions",
                    "MCQ Quiz",
                    "Quick Revision",
                    "Deep Explanation"
                ],
                value="Explain",
                label="🎯 Learning Mode"
            )

            generate = gr.Button(
                "🚀 Generate",
                variant="primary"
            )


        # ----------------------------------------------------
        # OUTPUT PANEL
        # ----------------------------------------------------

        with gr.Column(scale=2):

            output = gr.Markdown(
                value="### Your study material will appear here."
            )


    # --------------------------------------------------------
    # BUTTON
    # --------------------------------------------------------

    generate.click(
        fn=study_assistant,
        inputs=[
            subject,
            topic,
            level,
            task
        ],
        outputs=output
    )


# ============================================================
# 7. LAUNCH
# ============================================================

demo.launch(share=True)

